### PR TITLE
Build fixed (electrum-dash icon) and Exodus Update

### PR DESCRIPTION
**Pull request by emartec**
I had a problem with the build. A line related to the electrum-dash icon was not working, and simply removing it fixed it all. The icon is present.

BTW, Electrum-dash execution fail. It says something like "module not found: dns". I'll create an issue.

### CODE REVIEW

**Comment by estevaocm** [comment]
Thanks. Electrum-Dash issue is logged in #26

**Comment by emartec** [comment]
I don't understand....
How the "failed to execute" issue of electrum-dash is related to the vulnerability issue of  issue #26 ?

**Comment by estevaocm** [comment]
My last comment there was: "Electrum-Dash has been upgraded to solve the reported vulnerability, but is broken for lack of dependencies."

I have not succeeded in compiling the latest Electrum-Dash with Python in Bitkey, and decided not to downgrade due to the security issue. I asked the developer to package the dependencies as the other Electrum variants do, but had no response yet.

**Comment by estevaocm** [comment]
https://github.com/akhavr/electrum-dash/issues/12

**Comment by emartec** [comment]
Ok, good!

**Comment by estevaocm** [comment]
To be honest, I have not invested much time fixing this dependency issue. I could use some help.

**Comment by estevaocm** [comment]
Just found a dependencies package from an older version in another rep. Will make an attempt to compile the new one with it.

**Comment by estevaocm** [comment]
It worked!

**Comment by emartec** [comment]
Excellent!

**Pull request merged**
